targets:
  centos-7: true
  centos-8: true
  centos-9: true
  debian-10: true
  debian-11: true
  debian-12: true
  ubuntu-18.04: true
  ubuntu-20.04: true
  ubuntu-22.04: true
  sles-12: true
  sles-15: true
env:
  - "HELLO=world"
before:
  - 'echo "HELLO STDOUT: $HELLO"'
  - 'echo "HELLO STDERR: $HELLO" >&2'
services:
  - redis
  - postgres
