buildpack: https://github.com/pkgr/heroku-buildpack-ruby#universal-141
targets:
  debian-7: true
  ubuntu-12.04: true
  debian-8: true
  centos-6: false
  ubuntu-14.04: true
env:
  - "HELLO=world"
before:
  - 'echo "HELLO: $HELLO"'
services:
  - redis
  - postgres
