buildpack: https://github.com/pkgr/heroku-buildpack-ruby#v199-1
targets:
  debian-10: true
env:
  - "HELLO=world"
before:
  - 'echo "HELLO STDOUT: $HELLO"'
  - 'echo "HELLO STDERR: $HELLO" >&2'
services:
  - redis
  - postgres
