name: Package
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: app
          POSTGRES_USER: app
          POSTGRES_PASSWORD: p4ssw0rd
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        target:
          # - debian:11
          - el:10
          - ubuntu:26.04
          - sles:16
        #   - debian:12
        #   - debian:13
        #   - ubuntu:20.04
        #   - ubuntu:22.04
        #   - ubuntu:24.04
        #   - el:8
        #   - el:9
        #   - sles:15
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Package
        uses: pkgr/action/package@84f73e25c79dbc5c2bcfb996e9b96e88a15aef9c
        id: package
        with:
          target: ${{ matrix.target }}
          version: 0.1.0
          pkgr_version: 7a9a69d8736b90ff1af918dd1e4b84a5372df5a9
          # Keep this stable while changing the app commit to test toolchain restoration.
          cache_prefix: local-buildcurl-e2e
          debug: true
          env: |
            DATABASE_URL=postgres://app:p4ssw0rd@127.0.0.1:5432/app
      - name: Publish
        uses: pkgr/action/publish@84f73e25c79dbc5c2bcfb996e9b96e88a15aef9c
        with:
          target: ${{ matrix.target }}
          token: ${{ secrets.PACKAGER_PUBLISH_TOKEN }}
          repository: crohr/blank-sinatra-app
          channel: ${{ github.ref_name }}
          file: ${{ steps.package.outputs.package_path }}
