name: Package
on: [push]

jobs:
  build:
    name: Debian 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package@v1
        with:
          target: debian:12
          version: 1.0.0