name: Package
on: [push]

jobs:
  build:
    name: Debian 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: app
      - name: pkgr
        run: ls -al $GITHUB_WORKSPACE && docker run --rm -v $GITHUB_WORKSPACE/app:/app pkgr/debian:10 package .
